name: blood_pressure_bpm_tracker
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  hive_generator: ^2.0.1
  hive: ^2.2.3
  build_runner: ^2.3.3
  path_provider: ^2.1.1
  numberpicker: ^2.1.2
  loading_animation_widget: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true